version: '3'

services:
    nodejs-app:
        build: .
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "8080:8080" 
        networks:
            - ecommerce-net
        depends_on:
            - mongo1
            - mongo2
            - mongo3
    # mongo:
    #     container_name: mongo
    #     image: mongo
    #     restart: always
    #     volumes:
    #         - ./data:/data/db/mongo
    #     ports:
    #         - "27017:27017" 
    #     networks:
    #         - ecommerce-net
    redis:
        container_name: redis
        image: redis
        restart: always
        volumes:    
            - ./data:/data/db/redis
        ports:
            - "6380:6380" 
        networks:
            - ecommerce-net  
    mongo1:
        container_name: mongo1
        image: mongo:4.4
        volumes:
            - ~/mongors/data1:/data/db
            - ./rs-init.sh:/scripts/rs-init.sh
        networks:
            - ecommerce-net
        ports:
            - 27021:27017
        links:
            - mongo2
            - mongo3
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    mongo2:
        container_name: mongo2
        image: mongo:4.4
        volumes:
            - ~/mongors/data2:/data/db
        networks:
            - ecommerce-net
        ports:
            - 27022:27017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    mongo3:
        container_name: mongo3
        image: mongo:4.4
        volumes:
            - ~/mongors/data3:/data/db
        networks:
            - ecommerce-net
        ports:
            - 27023:27017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

    nginx: 
        build:
          context: ./src/api/v1/nginx
          dockerfile: Dockerfile
        container_name: nginx
        hostname: nginx
        ports:
            - "81:81" 
        depends_on:
            - nodejs-app
        networks:
            - ecommerce-net

networks:
  ecommerce-net:
    external: true